# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: CI-CD

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: CI
  displayName: 'Continuous Integration'
  jobs:
    - job: BuildAndTest
      displayName: 'Build do Projeto'
      steps:
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          projects: './src/Review-Filmes.sln'
      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: 'test'
          projects: './src/Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj'
    - job: Release
      displayName: 'Release Docker'
      dependsOn: BuildAndTest
      #steps: